# This is a Spack Environment file.
#
spack:
  packages:
    all:
      providers:
        target:
        - x86_64
        blas:
        - openblas
        mpi:
        - openmpi
  specs:
  - sundials +openmp +mpi +klu
  - raja
  - hdf5 +hl +mpi
  view: /opt/view
  concretizer:
    unify: true
  config:
    install_tree: /opt/software
