name: Containers - spack@latest

on:
  push: # testing
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build_containers:
    runs-on: ubuntu-22.04
    steps:
      - name: VM Hardware Info
        run: |
          cat /proc/cpuinfo
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.0.0
        with:
          context: "./docker"
          build-args: |
            tag=v0.19.0
            spack_yaml=./spack-latest.yaml
          push: true
          tags: ghcr.io/sundials-codes/sundials-demo-spack-latest:spack-latest
